name: Rust CI

on:
  push:
    branches:
      - jemalloc

jobs:
  measure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2025-02-20
          override: true
      - name: Run memory measurements
        run: |
          cargo run --bin measure --release
