name: Rust CI

on: workflow_dispatch

jobs:
  measure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1

      - name: Run memory measurements
        run: |
          cargo run --bin measure --release
